=== tue1501/CN_XML---UD/DTD_Buoi1/sinhvien.dtd
<!ELEMENT lop (sinhvien+)>

<!ELEMENT sinhvien (id, name, subjects)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT subjects (subject+)>
<!ELEMENT subject (subject_name, score)>
<!ELEMENT subject_name (#PCDATA)>
<!ELEMENT score (#PCDATA)>

=== tue1501/CN_XML---UD/Buoi1/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lop SYSTEM "../DTD_Buoi1/sinhvien.dtd">
<lop>
    <sinhvien>
        <id>SV001</id>
        <name>Nguyễn Văn A</name>
        <subjects>
            <subject>
                <subject_name>Lập trình Java</subject_name>
                <score>8.5</score>
            </subject>
            <subject>
                <subject_name>Cơ sở dữ liệu</subject_name>
                <score>7.8</score>
            </subject>
        </subjects>
    </sinhvien>

    <sinhvien>
        <id>SV002</id>
        <name>Trần Thị B</name>
        <subjects>
            <subject>
                <subject_name>Lập trình Python</subject_name>
                <score>9.0</score>
            </subject>
            <subject>
                <subject_name>Toán rời rạc</subject_name>
                <score>8.2</score>
            </subject>
        </subjects>
    </sinhvien>

    <sinhvien>
        <id>SV003</id>
        <name>Hoàng Minh C</name>
        <subjects>
            <subject>
                <subject_name>Hệ điều hành</subject_name>
                <score>7.5</score>
            </subject>
            <subject>
                <subject_name>Mạng máy tính</subject_name>
                <score>8.7</score>
            </subject>
        </subjects>
    </sinhvien>
</lop>
